name: Trigger auto deployment for infinitysearch

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/infinitysearch-AutoDeployTrigger-4a61c075-a6c5-43a7-9cd9-9faf22aff2f6.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.INFINITYSEARCH_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.INFINITYSEARCH_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.INFINITYSEARCH_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: infinity.azurecr.io
          registryUsername: ${{ secrets.INFINITYSEARCH_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.INFINITYSEARCH_REGISTRY_PASSWORD }}
          containerAppName: infinitysearch
          resourceGroup: rg-infinity
          imageToBuild: infinity.azurecr.io/infinitysearch:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


